name       : libidn2
version    : 2.3.0
release    : 8
source     :
    - https://ftp.gnu.org/gnu/libidn/libidn2-2.3.0.tar.gz : e1cb1db3d2e249a6a3eb6f0946777c2e892d5c5dc7bd91c74394fc3a01cab8b5
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : network.library
summary    : Internationalized domain name support library
description: |
    Libidn2 is a free software implementation of IDNA2008, Punycode and TR46. Its purpose is to encode and decode internationalized domain names.
emul32     : yes
builddeps  :
    - pkgconfig(gtk-doc)
    - libunistring-32bit-devel
patterns   :
    - devel : /usr/share/man/man3
    - docs : /usr/share/info
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
