name       : libidn2
version    : 2.1.1
release    : 6
source     :
    - https://ftp.gnu.org/gnu/libidn/libidn2-2.1.1.tar.lz : a99bb8c71bcf40b140be69518a002a5bc81ca9681bb8c2d3825f61671e957143
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : network.library
summary    : Internationalized domain name support library
description: |
    Libidn2 is a free software implementation of IDNA2008, Punycode and TR46. Its purpose is to encode and decode internationalized domain names.
emul32     : yes
builddeps  :
    - pkgconfig(gtk-doc)
    - libunistring-32bit-devel
patterns   :
    - devel : /usr/share/man/man3
    - docs : /usr/share/info
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
