name       : libidn2
version    : 2.02
release    : 1
source     :
    - https://ftp.gnu.org/gnu/libidn/libidn2-2.0.2.tar.lz : 5886c65ada48eb7bb0c03533ecad7f13048d998d2e1903428844aa001a920a5f
license    :
    - GPL-2.0
    - LGPL-3.0
component  : network.library
summary    : Internationalized domain name support library
description: |
    Libidn2 is a free software implementation of IDNA2008, Punycode and TR46. Its purpose is to encode and decode internationalized domain names.
emul32     : yes
builddeps  :
    - pkgconfig(gtk-doc)
    - libunistring-32bit-devel
    - libunistring-devel
patterns   :
    - devel: /usr/share/man/man3
    - docs : /usr/share/info
replaces   :
    - devel: libidn-devel
    - 32bit: libidn-32bit
    - 32bit-devel: libidn-32bit-devel
    - libidn
setup      : |
    %configure --disable-static \
               --prefix=/usr
build      : |
    %make
install    : |
    %make_install
