name       : libidn2
version    : 2.3.2
release    : 9
source     :
    - https://ftp.gnu.org/gnu/libidn/libidn2-2.3.2.tar.gz : 76940cd4e778e8093579a9d195b25fff5e936e9dc6242068528b437a76764f91
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : network.library
summary    : Internationalized domain name support library
description: |
    Libidn2 is a free software implementation of IDNA2008, Punycode and TR46. Its purpose is to encode and decode internationalized domain names.
emul32     : yes
builddeps  :
    - pkgconfig(gtk-doc)
    - libunistring-32bit-devel
patterns   :
    - devel : /usr/share/man/man3
    - docs : /usr/share/info
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
